### PR TITLE
Upgrade to Remix v2.6.0

### LINKED ISSUE #168: Upgrade to Remix 2.6.0
Quoting from the blog post [Open Sourcing the Remix Website
](https://remix.run/blog/oss-remix-dot-run)

> We invite you to explore and learn from the [source code](https://github.com/remix-run/remix-website)
> ...
> Open sourcing our website allows us to provide a real-world Remix site to learn from

I believe that if one of the ideas is to provide a real-world working site, it would be better to do it with the latest version of Remix.

Currently the website is using 2.5.1

I haven't used Vite so far, I'm waiting for it to become stable-stable to start using it on my projects, but I don't mind giving it a shot if you need help with this upgrade. I love solving issues :)

### PR DESCRIPTION
**Pull request by yoshimatsu567**
- Upgrade to Remix v2.6.0

Close #168

### CODE REVIEW

**Comment by brookslybrand** [comment]
Thanks @yoshimatsu567 for putting up this PR. There were a number of [breaking changes](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#patch-changes) to the unstable Vite plugin. Would you go through these and update everything that should be changed?

**Comment by brookslybrand** [comment]
@yoshimatsu567 I think you missed the ["Vite: Rely on Vite plugin ordering" change](https://github.com/remix-run/remix/blob/main/CHANGELOG.md#patch-changes)

```diff
  import mdx from "@mdx-js/rollup";
  import { unstable_vitePlugin as remix } from "@remix-run/dev";
  import { defineConfig } from "vite";

  export default defineConfig({
    plugins: [
+     mdx(),
      remix()
-     mdx(),
    ],
  });
```

**Comment by yoshimatsu567** [comment]
Thanks @brookslybrand for the review.
And sorry, I missed it. 🙇‍♂️

**Comment by brookslybrand** [comment]
> Thanks @brookslybrand for the review. And sorry, I missed it. 🙇‍♂️

No worries! It probably didn't really matter in this case, just good to put `remix()` last in case we ever do any other language processing first

**Review by brookslybrand — APPROVED** [review]
Thanks for this!

**Pull request merged**
