### PR TITLE
Add saasrock to showcase

### PR DESCRIPTION
**Pull request by AlexandroMtzG**
I saw [this tweet](https://twitter.com/BrooksLybrand/status/1757416856023863317) earlier today, so I'm taking my show at adding my commercial Remix SaaS boilerplate project ([saasrock](https://saasrock.com/)) 😁.

### CODE REVIEW

**Comment by brookslybrand** [comment]
Hey @AlexandroMtzG, thanks for putting this up!

Genuine question, how do you feel about this being a [Resource](https://remix.run/resources) instead? At first glance it feels a bit more in line with the resources, vs the showcase being websites built in Remix (though I realize your site is built in Remix as well)

**Comment by AlexandroMtzG** [comment]
Hi Brooks, all the resources are open source and this one is not. But I agree is not a 100% showcase item as well, I just had to try : )

**Comment by brookslybrand** [comment]
> Hi Brooks, all the resources are open source and this one is not. But I agree is not a 100% showcase item as well, I just had to try : )

Totally valid, the way we have resources setup you have to be pointed to a GitHub repo 🤔

I need to make the Resource pages a bit more robust anyway, so this is a useful use case for helping me think through how the data should be structured.

I'll keep thinking on it and get back to you. I really appreciate you putting up the PR

**Comment by AlexandroMtzG** [comment]
Thank you Brooks :D I already appear in a [Resource](https://remix.run/resources/remix-page-blocks) so that's already awesome for me. Thanks!

**Comment by brookslybrand** [comment]
Hey @AlexandroMtzG, I'm going to go ahead and merge this PR. At some point I will need to prune through these examples and update with a list of new sites. At that point I may remove saasrock and try to focus more on end-products. I hope you understand in advance

Good luck with continuing to build SaasRock!

**Comment by AlexandroMtzG** [comment]
Thanks @brookslybrand! Totally understand, thank you 😁

**Pull request merged**
