### PR TITLE
Add Atmos Financial to showcase

### PR DESCRIPTION
**Pull request by nikodunk**
Based on [this tweet](https://twitter.com/BrooksLybrand/status/1757416856023863317) - Adding Atmos Financial to showcase.

Our web app (https://www.joinatmos.com, hit login or apply) runs on Remix, and we love it. Our mobile app re-uses the pages in webviews. Thank you!

@brookslybrand

**Screenshot**
Screenshot 2024-05-02 at 12 23 58 PM

### CODE REVIEW

**Comment by brookslybrand** [comment]
Hi @nikodunk, I'm sorry for the delay

Very cool you're using Remix! I don't think the login wizard really works well for a showcase page. Is there anything behind auth built in Remix that would be impressive and that you could show with test data or something?

**Comment by nikodunk** [comment]
@brookslybrand great call! Updated it with a demo login as our demo user. Let me know if you have any other suggestions!

**Comment by brookslybrand** [comment]
Hey @nikodunk, thanks for following up! I'm sorry I've been slow to review and get this merged in

I'm actually a little blocked by #273, since I currently have to limit the number of showcase examples shown. I need to find some time to work on this, at which point I should be able to merge this in

**Comment by nikodunk** [comment]
Thanks @brookslybrand - sounds good! Very excited to get up on the showcase page when you're ready. We're proud to be using it!

**Pull request merged**
