### PR TITLE
Add SaaSKits to Remix showcase

### PR DESCRIPTION
**Pull request by thandaanda**
Based on this [tweet](https://twitter.com/BrooksLybrand/status/1757416856023863317?s=20) - Adding SaaSKits to showcase.

We have built Open Source boilerplate for Remix community to get started with their SaaS quickly.

Our next changes are integrating Vite and adding PostgreSQL as DB option.

@brookslybrand

### CODE REVIEW

**Comment by brookslybrand** [comment]
Hey thanks for the PR! I think this is a better fit for the [resources page](https://remix.run/resources/) ([.yaml file](https://github.com/remix-run/remix-website/blob/main/data/resources.yaml))

**Comment by thandaanda** [comment]
@brookslybrand Moved SaaSKits from showcase to resources.

**Comment by thandaanda** [comment]
@brookslybrand Let me know if something is missing on our end.

**Comment by brookslybrand** [comment]
Done! Thanks for making the change @thandaanda

**Pull request merged**
